### ISSUE TITLE
Curious to how this was made

### ISSUE THREAD

**Issue by huantianad** [sjx233/rdlevel-schema#1]
Hey, just wanted to ask how the json schema for levels were made? Did you use some script to generate it?

**Comment by 0f-0b** [comment]
It was originally handwritten in TypeScript and later converted to JSON schema.

**Comment by huantianad** [comment]
Ah I was just wondering because I'm setting models for rdlevels in pydantic, and was wondering if there was a good way of doing all the events other than just by hands.
